-- Refresh Adapta Brasil CCRA facts from staging into modelled table.
--DELETE FROM modelled.city_adapta_risk_fact
--WHERE source_dataset = 'br-mcti/adaptabrasil';

INSERT INTO modelled.city_adapta_risk_fact (
    actor_id,
    city_name,
    country_code,
    timeframe,
    scenario,
    scenario_family,
    sector_id,
    sector_name,
    risk_id,
    risk_name,
    risk_component_id,
    risk_component_name,
    impact_chain_id_1,
    impact_chain_name_1,
    impact_chain_id_2,
    impact_chain_name_2,
    impact_chain_id_3,
    impact_chain_name_3,
    base_indicator_id,
    base_indicator_name,
    base_indicator_level,
    risk_value_numeric,
    risk_value_string,
    risk_component_value_numeric,
    risk_component_value_string,
    impact_chain_1_value_numeric,
    impact_chain_1_value_string,
    impact_chain_2_value_numeric,
    impact_chain_2_value_string,
    impact_chain_3_value_numeric,
    impact_chain_3_value_string,
    base_indicator_value_numeric,
    base_indicator_value_string,
    null_type,
    release_id,
    source_dataset,
    release_version,
    source_vintage,
    spatial_support_level
)
SELECT
    NULLIF(BTRIM(actor_id::TEXT), ''),
    city_name,
    COALESCE(NULLIF(BTRIM(country_code::TEXT), ''), 'BR'),
    timeframe::INTEGER,
    scenario,
    NULLIF(BTRIM(scenario_family::TEXT), ''),
    sector_id::INTEGER,
    NULLIF(BTRIM(sector_name::TEXT), ''),
    risk_id::INTEGER,
    risk_name,
    risk_component_id::INTEGER,
    NULLIF(BTRIM(risk_component_name::TEXT), ''),
    impact_chain_id_1::INTEGER,
    NULLIF(BTRIM(impact_chain_name_1::TEXT), ''),
    impact_chain_id_2::INTEGER,
    NULLIF(BTRIM(impact_chain_name_2::TEXT), ''),
    impact_chain_id_3::INTEGER,
    NULLIF(BTRIM(impact_chain_name_3::TEXT), ''),
    base_indicator_id::INTEGER,
    NULLIF(BTRIM(base_indicator_name::TEXT), ''),
    base_indicator_level::INTEGER,
    risk_value_numeric::NUMERIC(10, 4),
    NULLIF(BTRIM(risk_value_string::TEXT), ''),
    risk_component_value_numeric::NUMERIC(10, 4),
    NULLIF(BTRIM(risk_component_value_string::TEXT), ''),
    impact_chain_1_value_numeric::NUMERIC(10, 4),
    NULLIF(BTRIM(impact_chain_1_value_string::TEXT), ''),
    impact_chain_2_value_numeric::NUMERIC(10, 4),
    NULLIF(BTRIM(impact_chain_2_value_string::TEXT), ''),
    impact_chain_3_value_numeric::NUMERIC(10, 4),
    NULLIF(BTRIM(impact_chain_3_value_string::TEXT), ''),
    base_indicator_value_numeric::NUMERIC(10, 4),
    NULLIF(BTRIM(base_indicator_value_string::TEXT), ''),
    COALESCE(NULLIF(BTRIM(null_type::TEXT), ''), 'none'),
    NULLIF(BTRIM(release_id::TEXT), '')::UUID,
    source_dataset,
    NULLIF(BTRIM(release_version::TEXT), ''),
    NULLIF(BTRIM(source_vintage::TEXT), ''),
    spatial_support_level
FROM raw_data.risk_profile_staging
WHERE COALESCE(NULLIF(BTRIM(source_dataset::TEXT), ''), 'br-mcti/adaptabrasil') = 'br-mcti/adaptabrasil';
