INSERT INTO modelled.emissions (
    emissions_id,
    datasource_name,
    actor_id,
    city_id,
    gpc_reference_number,
    emissions_value,
    emissions_year,
    emissions_units,
    gpcmethod_id,
    gas_name,
    emissionfactor_id,
    activity_id,
    activity_value,
    spatial_granularity,
    geometry_type,
    geometry,
    geometry_id
)
 SELECT 
    emissions_id,
    datasource_name,
    actor_id,
    city_id,
    gpc_reference_number,
    SUM(emissions_value::numeric*1000) as emissions_value,
    emissions_year,
    'kg' as emissions_units,
    gpcmethod_id,
    gas_name,
    emissionfactor_id,
    activity_id,
    SUM(activity_value) as activity_value,
    'city' as spatial_granularity,
    geometry_type,
    geometry,
    geometry_id
FROM raw_data.carbonmonitor_staging_v2025
GROUP BY emissions_id, datasource_name, actor_id, city_id, gpc_reference_number, emissions_year, gpcmethod_id, gas_name, emissionfactor_id, activity_id, geometry_type, geometry, geometry_id
HAVING SUM(emissions_value::numeric*1000) > 1
ON CONFLICT (emissions_id) DO UPDATE SET
    datasource_name = EXCLUDED.datasource_name,
    actor_id = EXCLUDED.actor_id,
    city_id = EXCLUDED.city_id,
    gpc_reference_number = EXCLUDED.gpc_reference_number,
    emissions_value = EXCLUDED.emissions_value,
    emissions_year = EXCLUDED.emissions_year,
    emissions_units = EXCLUDED.emissions_units,
    gpcmethod_id = EXCLUDED.gpcmethod_id,
    gas_name = EXCLUDED.gas_name,
    emissionfactor_id = EXCLUDED.emissionfactor_id,
    activity_id = EXCLUDED.activity_id,
    activity_value = EXCLUDED.activity_value,
    spatial_granularity = EXCLUDED.spatial_granularity,
    geometry_type = EXCLUDED.geometry_type,
    geometry = EXCLUDED.geometry,
    geometry_id = EXCLUDED.geometry_id;