INSERT INTO modelled.emissions (
    emissions_id,
    datasource_name,
    actor_id,
    city_id,
    gpc_reference_number,
    emissions_value,
    emissions_year,
    emissions_units,
    gpcmethod_id,
    gas_name,
    emissionfactor_id,
    activity_id,
    activity_value,
    spatial_granularity,
    geometry_type,
    geometry,
    geometry_id
)
 SELECT 
    emissions_id,
    datasource_name,
    actor_id,
    city_id,
    gpc_reference_number,
    emissions_value::numeric as emissions_value,
    emissions_year,
    'kg' as emissions_units,
    method_id as gpcmethod_id,
    upper(gas_name) as gas_name,
    emissionfactor_id,
    activity_id,
    activity_value,
    'city' as spatial_granularity,
    geometry_type,
    geometry,
    geometry_id
FROM raw_data.arg_solid_waste_indec
ON CONFLICT (emissions_id) DO UPDATE SET
    datasource_name = EXCLUDED.datasource_name,
    actor_id = EXCLUDED.actor_id,
    city_id = EXCLUDED.city_id,
    gpc_reference_number = EXCLUDED.gpc_reference_number,
    emissions_value = EXCLUDED.emissions_value,
    emissions_year = EXCLUDED.emissions_year,
    emissions_units = EXCLUDED.emissions_units,
    gpcmethod_id = EXCLUDED.gpcmethod_id,
    gas_name = EXCLUDED.gas_name,
    emissionfactor_id = EXCLUDED.emissionfactor_id,
    activity_id = EXCLUDED.activity_id,
    activity_value = EXCLUDED.activity_value,
    spatial_granularity = EXCLUDED.spatial_granularity,
    geometry_type = EXCLUDED.geometry_type,
    geometry = EXCLUDED.geometry,
    geometry_id = EXCLUDED.geometry_id;