DROP TABLE IF EXISTS raw_data.keyimpact_hazard_indictor;

CREATE TABLE raw_data.keyimpact_hazard_indictor AS 
SELECT * FROM (
    VALUES 
    ('water resources', 'drought', 'hazard', 'consecutive dry days', 'positive', 'Adapta'),
    ('water resources', 'drought', 'hazard', 'standardized precipitation evapotranspiration index', 'positive', 'Adapta'),
    ('water resources', 'drought', 'vulnerability', 'inadequate water access', 'positive', 'IBGE'),
    ('water resources', 'drought', 'vulnerability', 'income', 'positive', 'IBGE'),
    ('water resources', 'drought', 'vulnerability', 'water security index', 'positive', 'ANA'),
    ('water resources', 'drought', 'exposure', 'population density', 'positive', 'IBGE'),
    ('water resources', 'drought', 'exposure', 'nutrition and basic medical care', 'positive', 'IPS'),
    ('geo-hydrological disasters', 'landslide', 'hazard', 'landslide threat index', 'positive', 'Adapta'),
    ('geo-hydrological disasters', 'landslide', 'vulnerability', 'income', 'positive', 'IBGE'),
    ('geo-hydrological disasters', 'landslide', 'vulnerability', 'age distribution', 'positive', 'IBGE'),
    ('geo-hydrological disasters', 'landslide', 'vulnerability', 'forest and non-forest natural cover', 'positive', 'MapBiomas'),
    ('geo-hydrological disasters', 'landslide', 'exposure', 'population density', 'positive', 'IBGE'),
    ('geo-hydrological disasters', 'landslide', 'exposure', 'houses in risk areas', 'positive', 'Adapta'),
    ('energy security', 'drought', 'hazard', 'consecutive dry days', 'positive', 'Adapta'),
    ('energy security', 'drought', 'vulnerability', 'electricity consumption', 'positive', 'ANEL'),
    ('energy security', 'drought', 'vulnerability', 'income', 'positive', 'IBGE'),
    ('energy security', 'drought', 'vulnerability', 'energy poverty', 'positive', 'Adapta'),
    ('energy security', 'drought', 'exposure', 'population density', 'positive', 'IBGE'),
    ('energy security', 'drought', 'exposure', 'energy power plants', 'positive', 'EPE'),
    ('energy security', 'heatwaves', 'hazard', 'maximum temperature', 'positive', 'Adapta'),
    ('energy security', 'heatwaves', 'exposure', 'population density', 'positive', 'IBGE'),
    ('energy security', 'heatwaves', 'exposure', 'energy power plants', 'positive', 'EPE'),
    ('energy security', 'heatwaves', 'vulnerability', 'electricity consumption', 'positive', 'ANEL'),
    ('energy security', 'heatwaves', 'vulnerability', 'income', 'positive', 'IBGE'),
    ('energy security', 'heatwaves', 'vulnerability', 'energy poverty', 'positive', 'Adapta'),
    ('food security', 'drought', 'hazard', 'standardized precipitation evapotranspiration index', 'positive', 'Adapta'),
    ('food security', 'drought', 'hazard', 'consecutive dry days', 'positive', 'Adapta'),
    ('food security', 'drought', 'vulnerability', 'income', 'positive', 'IBGE'),
    ('food security', 'drought', 'vulnerability', 'production and commercialisation of food', 'positive', 'Adapta'),
    ('food security', 'drought', 'vulnerability', 'dependence on large scale irrigation', 'positive', 'Adapta'),
    ('food security', 'drought', 'exposure', 'economic dependency on agriculture', 'positive', 'Adapta'),
    ('food security', 'drought', 'exposure', 'population density', 'positive', 'IBGE'),
    ('food security', 'drought', 'exposure', 'municipal agricultural area', 'positive', 'IBGE'),
    ('food security', 'drought', 'exposure', 'density of agricultural establishments', 'positive', 'Adapta'),
    ('food security', 'drought', 'exposure', 'nutrition and basic medical care', 'positive', 'IPS'),
    ('food security', 'flooding', 'hazard', 'maximum precipitation 5 days', 'positive', 'Adapta'),
    ('food security', 'flooding', 'hazard', 'total precipitation', 'positive', 'Adapta'),
    ('food security', 'flooding', 'vulnerability', 'income', 'positive', 'IBGE'),
    ('food security', 'flooding', 'vulnerability', 'production and commercialisation of food', 'positive', 'Adapta'),
    ('food security', 'flooding', 'exposure', 'economic dependency on agriculture', 'positive', 'Adapta'),
    ('food security', 'flooding', 'exposure', 'population density', 'positive', 'IBGE'),
    ('food security', 'flooding', 'exposure', 'municipal agricultural area', 'positive', 'IBGE'),
    ('food security', 'flooding', 'exposure', 'density of agricultural establishments', 'positive', 'IBGE'),
    ('food security', 'flooding', 'exposure', 'nutrition and basic medical care', 'positive', 'IPS')
) AS t(keyimpact_name, hazard_name, component, indicator_name, relationship, datasource);