DROP TABLE IF EXISTS raw_data.keyimpact_hazard_indictor;

CREATE TABLE raw_data.keyimpact_hazard_indictor AS 
SELECT * FROM (
    VALUES 
    ('water resources', 'droughts', 'hazard', 'consecutive dry days', 'positive', 'Adapta'),
    ('water resources', 'droughts', 'hazard', 'standardized precipitation evapotranspiration index', 'positive', 'Adapta'),
    ('water resources', 'droughts', 'vulnerability', 'inadequate water access', 'positive', 'IBGE'),
    ('water resources', 'droughts', 'vulnerability', 'income', 'positive', 'IBGE'),
    ('water resources', 'droughts', 'vulnerability', 'water security index', 'positive', 'ANA'),
    ('water resources', 'droughts', 'exposure', 'population', 'positive', 'IBGE'),
    ('water resources', 'droughts', 'vulnerability', 'water loss rate', 'positive', 'IPS'),
    ('energy security', 'droughts', 'hazard', 'standardized precipitation evapotranspiration index', 'positive', 'Adapta'),
    ('energy security', 'droughts', 'vulnerability', 'income', 'positive', 'IBGE'),
    ('energy security', 'droughts', 'vulnerability', 'energy poverty', 'positive', 'Adapta'),
    ('energy security', 'droughts', 'exposure', 'population', 'positive', 'IBGE'),
    ('energy security', 'droughts', 'exposure', 'energy power plants', 'positive', 'EPE'),
    ('energy security', 'heatwaves', 'hazard', 'maximum temperature', 'positive', 'Adapta'),
    ('energy security', 'heatwaves', 'exposure', 'population', 'positive', 'IBGE'),
    ('energy security', 'heatwaves', 'exposure', 'energy power plants', 'positive', 'EPE'),
    ('energy security', 'heatwaves', 'vulnerability', 'income', 'positive', 'IBGE'),
    ('energy security', 'heatwaves', 'vulnerability', 'energy poverty', 'positive', 'Adapta'),
    ('food security', 'droughts', 'hazard', 'standardized precipitation evapotranspiration index', 'positive', 'Adapta'),
    ('food security', 'droughts', 'hazard', 'consecutive dry days', 'positive', 'Adapta'),
    ('food security', 'droughts', 'vulnerability', 'income', 'positive', 'IBGE'),
    ('food security', 'droughts', 'vulnerability', 'malnutrition', 'positive', 'IPS'),
    ('food security', 'droughts', 'vulnerability', 'age distribution', 'positive', 'IBGE'),
    ('food security', 'droughts', 'vulnerability', 'agriculture gdp', 'positive', 'IBGE'),
    ('food security', 'droughts', 'exposure', 'population', 'positive', 'IBGE'),
    ('food security', 'droughts', 'exposure', 'municipal agricultural area', 'positive', 'IBGE'),
    ('food security', 'floods', 'hazard', 'maximum precipitation 5 days', 'positive', 'Adapta'),
    ('food security', 'floods', 'hazard', 'total precipitation', 'positive', 'Adapta'),
    ('food security', 'floods', 'vulnerability', 'income', 'positive', 'IBGE'),
    ('food security', 'floods', 'vulnerability', 'malnutrition', 'positive', 'IPS'),
    ('food security', 'floods', 'vulnerability', 'age distribution', 'positive', 'IBGE'),
    ('food security', 'floods', 'vulnerability', 'agriculture gdp', 'positive', 'IBGE'),
    ('food security', 'floods', 'exposure', 'population', 'positive', 'IBGE'),
    ('food security', 'floods', 'exposure', 'municipal agricultural area', 'positive', 'IBGE'),
    ('public health', 'diseases', 'hazard', 'relative humidity', 'positive', 'Adapta'),
    ('public health', 'diseases', 'hazard', 'maximum precipitation 5 days', 'positive', 'Adapta'),
    ('public health', 'diseases', 'hazard', 'maximum temperature', 'positive', 'Adapta'),
    ('public health', 'diseases', 'hazard', 'precipitation intensity', 'positive', 'Adapta'),
    ('public health', 'diseases', 'vulnerability', 'confirmed cases of diseases', 'positive', 'DataSUS'),
    ('public health', 'diseases', 'vulnerability', 'health establishments', 'negative', 'DatosGov'),
    ('public health', 'diseases', 'vulnerability', 'inadequate sanitation', 'positive', 'IBGE'),
    ('public health', 'diseases', 'vulnerability', 'inadequate water access', 'positive', 'IBGE'),
    ('public health', 'diseases', 'vulnerability', 'malnutrition', 'positive', 'IPS'),
    ('public health', 'diseases', 'vulnerability', 'deforested area', 'positive', 'IPS'), -- need to add
    ('public health', 'diseases', 'vulnerability', 'age distribution', 'positive', 'IBGE'),
    ('public health', 'diseases', 'vulnerability', 'waste collection', 'positive', 'IBGE'),
    ('public health', 'diseases', 'exposure', 'population', 'positive', 'IBGE'),
    ('public health', 'heatwaves', 'hazard', 'maximum temperature', 'positive', 'Adapta'),
    ('public health', 'heatwaves', 'vulnerability', 'health establishments', 'negative', 'DatosGov'),
    ('public health', 'heatwaves', 'vulnerability', 'income', 'positive', 'IBGE'),
    ('public health', 'heatwaves', 'vulnerability', 'age distribution', 'positive', 'IBGE'),
    ('public health', 'heatwaves', 'vulnerability', 'malnutrition', 'positive', 'IPS'),
    ('public health', 'heatwaves', 'exposure', 'population', 'positive', 'IBGE'),
    -- added new hazard
    ('public health', 'landslides', 'hazard', 'landslide threat index', 'positive', 'Adapta'),
    ('public health', 'landslides', 'vulnerability', 'income', 'positive', 'IBGE'),
    ('public health', 'landslides', 'vulnerability', 'age distribution', 'positive', 'IBGE'),
    ('public health', 'landslides', 'vulnerability', 'urban green area', 'positive', 'MapBiomass'),
    ('public health', 'landslides', 'exposure', 'population density', 'positive', 'IBGE'),
    ('public health', 'landslides', 'exposure', 'houses in risk areas', 'positive', 'Adapta'),
    ('public health', 'floods', 'hazard', 'flood threat index', 'positive', 'Adapta'),
    ('public health', 'floods', 'vulnerability', 'income', 'positive', 'IBGE'),
    ('public health', 'floods', 'vulnerability', 'age distribution', 'positive', 'IBGE'),
    ('public health', 'floods', 'vulnerability', 'urban green area', 'negative', 'MapBiomass'),
    ('public health', 'floods', 'vulnerability', 'coverage rate of public urban drainage', 'positive', 'SNIS'), -- need indicator
    ('public health', 'floods', 'exposure', 'population density', 'positive', 'IBGE'),
    ('public health', 'floods', 'exposure', 'houses in risk areas', 'positive', 'Adapta'),
    -- added ended
    ('infrastructure', 'sea-level-rise', 'hazard', 'sea level change', 'positive', 'SeaLevelRiseProjection'),
    ('infrastructure', 'sea-level-rise', 'vulnerability', 'industry gdp', 'positive', 'IBGE'),
    ('infrastructure', 'sea-level-rise', 'vulnerability', 'social vulnerability urban infrastructure index', 'negative', 'IPEA'),
    ('infrastructure', 'sea-level-rise', 'exposure', 'port infrastructure', 'positive', 'ANTAQ'),
    ('infrastructure', 'sea-level-rise', 'exposure', 'population', 'positive', 'IBGE'),
    ('infrastructure', 'landslides', 'hazard', 'landslide threat index', 'positive', 'Adapta'),
    ('infrastructure', 'landslides', 'vulnerability', 'forest and non-forest natural cover', 'positive', 'IPS'),
    ('infrastructure', 'landslides', 'vulnerability', 'industry gdp', 'positive', 'IBGE'),
    ('infrastructure', 'landslides', 'vulnerability', 'social vulnerability urban infrastructure index', 'negative', 'IPEA'),
    ('infrastructure', 'landslides', 'exposure', 'road density', 'positive', 'Ministry of Transport'),
    ('infrastructure', 'landslides', 'exposure', 'railroad density', 'positive', 'Ministry of Transport'),
    ('infrastructure', 'floods', 'hazard', 'flood threat index', 'positive', 'Adapta'),
    ('infrastructure', 'floods', 'vulnerability', 'industry gdp', 'positive', 'IBGE'),
    ('infrastructure', 'floods', 'vulnerability', 'urban green area', 'negative', 'MapBiomass'),
    ('infrastructure', 'floods', 'vulnerability', 'social vulnerability urban infrastructure index', 'negative', 'IPEA'),
    ('infrastructure', 'floods', 'exposure', 'road density', 'positive', 'Ministry of Transport'),
    ('infrastructure', 'floods', 'exposure', 'railroad density', 'positive', 'Ministry of Transport'),
    ('infrastructure', 'heatwaves', 'hazard', 'maximum temperature', 'positive', 'Adapta'),
    ('infrastructure', 'heatwaves', 'vulnerability', 'industry gdp', 'positive', 'IBGE'),
    ('infrastructure', 'heatwaves', 'vulnerability', 'forest and non-forest natural cover', 'negative', 'IPS'),
    ('infrastructure', 'heatwaves', 'vulnerability', 'social vulnerability urban infrastructure index', 'negative', 'IPEA'),
    ('infrastructure', 'heatwaves', 'exposure', 'road density', 'positive', 'Ministry of Transport'),
    ('infrastructure', 'heatwaves', 'exposure', 'railroad density', 'positive', 'Ministry of Transport'),
    ('biodiversity', 'droughts', 'hazard', 'consecutive dry days', 'positive', 'Adapta'),
    ('biodiversity', 'droughts', 'hazard', 'standardized precipitation evapotranspiration index', 'positive', 'Adapta'),
    ('biodiversity', 'droughts', 'vulnerability', 'biodiversity intactness index', 'positive', 'EarthEngine'),
    ('biodiversity', 'droughts', 'vulnerability', 'areas of global conservation value', 'positive', 'EarthEngine'),
    ('biodiversity', 'droughts', 'exposure', 'protected area', 'positive', 'WDPA'),
    ('biodiversity', 'droughts', 'exposure', 'forest and non-forest natural cover', 'positive', 'MapBiomass'),
    ('biodiversity', 'heatwaves', 'hazard', 'maximum temperature', 'positive', 'Adapta'),
    ('biodiversity', 'heatwaves', 'vulnerability', 'biodiversity intactness index', 'positive', 'EarthEngine'),
    ('biodiversity', 'heatwaves', 'vulnerability', 'areas of global conservation value', 'positive', 'EarthEngine'),
    ('biodiversity', 'heatwaves', 'exposure', 'protected area', 'positive', 'WDPA'),
    ('biodiversity', 'heatwaves', 'exposure', 'forest and non-forest natural cover', 'positive', 'MapBiomass')
) AS t(keyimpact_name, hazard_name, component, indicator_name, relationship, datasource);