DROP TABLE IF EXISTS raw_data.keyimpact_hazard_indictor;

CREATE TABLE raw_data.keyimpact_hazard_indictor AS 
SELECT * FROM (
    VALUES 
    ('water resources', 'drought', 'hazard', 'consecutive dry days', 'positive', 'Adapta'),
    ('water resources', 'drought', 'hazard', 'standardized precipitation evapotranspiration index', 'positive', 'Adapta'),
    ('water resources', 'drought', 'vulnerability', 'inadequate water access', 'positive', 'IBGE'),
    ('water resources', 'drought', 'vulnerability', 'income', 'positive', 'IBGE'),
    ('water resources', 'drought', 'vulnerability', 'water security index', 'positive', 'ANA'),
    ('water resources', 'drought', 'exposure', 'population density', 'positive', 'IBGE'),
    ('water resources', 'drought', 'exposure', 'nutrition and basic medical care', 'positive', 'IPS'),
    ('geo-hydrological disasters', 'landslide', 'hazard', 'landslide threat index', 'positive', 'Adapta'),
    ('geo-hydrological disasters', 'landslide', 'vulnerability', 'income', 'positive', 'IBGE'),
    ('geo-hydrological disasters', 'landslide', 'vulnerability', 'age distribution', 'positive', 'IBGE'),
    ('geo-hydrological disasters', 'landslide', 'vulnerability', 'forest and non-forest natural cover', 'positive', 'MapBiomas'),
    ('geo-hydrological disasters', 'landslide', 'exposure', 'population density', 'positive', 'IBGE'),
    ('geo-hydrological disasters', 'landslide', 'exposure', 'houses in risk areas', 'positive', 'Adapta'),
    ('energy security', 'drought', 'hazard', 'consecutive dry days', 'positive', 'Adapta'),
    ('energy security', 'drought', 'vulnerability', 'electricity consumption', 'positive', 'ANEL'),
    ('energy security', 'drought', 'vulnerability', 'income', 'positive', 'IBGE'),
    ('energy security', 'drought', 'vulnerability', 'energy poverty', 'positive', 'Adapta'),
    ('energy security', 'drought', 'exposure', 'population density', 'positive', 'IBGE'),
    ('energy security', 'drought', 'exposure', 'energy power plants', 'positive', 'EPE'),
    ('energy security', 'heatwaves', 'hazard', 'maximum temperature', 'positive', 'Adapta'),
    ('energy security', 'heatwaves', 'exposure', 'population density', 'positive', 'IBGE'),
    ('energy security', 'heatwaves', 'exposure', 'energy power plants', 'positive', 'EPE'),
    ('energy security', 'heatwaves', 'vulnerability', 'electricity consumption', 'positive', 'ANEL'),
    ('energy security', 'heatwaves', 'vulnerability', 'income', 'positive', 'IBGE'),
    ('energy security', 'heatwaves', 'vulnerability', 'energy poverty', 'positive', 'Adapta'),
    ('food security', 'drought', 'hazard', 'standardized precipitation evapotranspiration index', 'positive', 'Adapta'),
    ('food security', 'drought', 'hazard', 'consecutive dry days', 'positive', 'Adapta'),
    ('food security', 'drought', 'vulnerability', 'income', 'positive', 'IBGE'),
    ('food security', 'drought', 'vulnerability', 'production and commercialisation of food', 'positive', 'Adapta'),
    ('food security', 'drought', 'vulnerability', 'dependence on large scale irrigation', 'positive', 'Adapta'),
    ('food security', 'drought', 'exposure', 'economic dependency on agriculture', 'positive', 'Adapta'),
    ('food security', 'drought', 'exposure', 'population density', 'positive', 'IBGE'),
    ('food security', 'drought', 'exposure', 'municipal agricultural area', 'positive', 'IBGE'),
    ('food security', 'drought', 'exposure', 'density of agricultural establishments', 'positive', 'Adapta'),
    ('food security', 'drought', 'exposure', 'nutrition and basic medical care', 'positive', 'IPS'),
    ('food security', 'drought', 'exposure', 'agriculture gdp', 'positive', 'IBGE'),
    ('food security', 'flooding', 'hazard', 'maximum precipitation 5 days', 'positive', 'Adapta'),
    ('food security', 'flooding', 'hazard', 'total precipitation', 'positive', 'Adapta'),
    ('food security', 'flooding', 'vulnerability', 'income', 'positive', 'IBGE'),
    ('food security', 'flooding', 'vulnerability', 'production and commercialisation of food', 'positive', 'Adapta'),
    ('food security', 'flooding', 'exposure', 'economic dependency on agriculture', 'positive', 'Adapta'),
    ('food security', 'flooding', 'exposure', 'population density', 'positive', 'IBGE'),
    ('food security', 'flooding', 'exposure', 'municipal agricultural area', 'positive', 'IBGE'),
    ('food security', 'flooding', 'exposure', 'density of agricultural establishments', 'positive', 'Adapta'),
    ('food security', 'flooding', 'exposure', 'nutrition and basic medical care', 'positive', 'IPS'),
    ('food security', 'flooding', 'exposure', 'agriculture gdp', 'positive', 'IBGE'),
    ('geo-hydrological disasters', 'flooding', 'hazard', 'flood threat index', 'positive', 'Adapta'),
    ('geo-hydrological disasters', 'flooding', 'vulnerability', 'income', 'positive', 'IBGE'),
    ('geo-hydrological disasters', 'flooding', 'vulnerability', 'age distribution', 'positive', 'IBGE'),
    ('geo-hydrological disasters', 'flooding', 'vulnerability', 'coverage rate of public urban drainage', 'positive', 'SNIS'),
    ('geo-hydrological disasters', 'flooding', 'exposure', 'population density', 'positive', 'IBGE'),
    ('geo-hydrological disasters', 'flooding', 'exposure', 'houses in risk areas', 'positive', 'IBGE'),
    ('public health', 'diseases', 'hazard', 'relative humidity', 'positive', 'Adapta'),
    ('public health', 'diseases', 'hazard', 'maximum precipitation 5 days', 'positive', 'Adapta'),
    ('public health', 'diseases', 'vulnerability', 'confirmed cases of diseases', 'positive', 'DataSUS'),
    ('public health', 'diseases', 'vulnerability', 'health establishments', 'negative', 'DatosGov'),
    ('public health', 'diseases', 'vulnerability', 'inadequate sanitation', 'positive', 'IBGE'),
    ('public health', 'diseases', 'vulnerability', 'inadequate water access', 'positive', 'IBGE'),
    ('public health', 'diseases', 'vulnerability', 'income', 'positive', 'IBGE'),
    ('public health', 'diseases', 'vulnerability', 'age distribution', 'positive', 'IBGE'),
    ('public health', 'diseases', 'vulnerability', 'waste collection', 'positive', 'IBGE'),
    ('public health', 'diseases', 'exposure', 'population density', 'positive', 'IBGE'),
    ('public health', 'heatwaves', 'hazard', 'maximum temperature', 'positive', 'Adapta'),
    ('public health', 'heatwaves', 'vulnerability', 'health establishments', 'negative', 'DatosGov'),
    ('public health', 'heatwaves', 'vulnerability', 'income', 'positive', 'IBGE'),
    ('public health', 'heatwaves', 'vulnerability', 'age distribution', 'positive', 'IBGE'),
    ('public health', 'heatwaves', 'exposure', 'population density', 'positive', 'IBGE'),
    ('infrastructure', 'sea level rise', 'hazard', 'sea level change', 'positive', 'SeaLevelRiseProjection'),
    ('infrastructure', 'sea level rise', 'vulnerability', 'industry gdp', 'positive', 'IBGE'),
    ('infrastructure', 'sea level rise', 'exposure', 'port infrastructure', 'positive', 'ANTAQ'),
    ('infrastructure', 'sea level rise', 'exposure', 'population density', 'positive', 'IBGE'),
    ('infrastructure', 'sea level rise', 'exposure', 'social vulnerability urban infrastructure index', 'negative', 'IPEA'),
    ('infrastructure', 'landslide', 'hazard', 'landslide threat index', 'positive', 'Adapta'),
    ('infrastructure', 'landslide', 'vulnerability', 'landslide susceptibility', 'positive', 'WorldBank'),
    ('infrastructure', 'landslide', 'vulnerability', 'industry gdp', 'positive', 'IBGE'),
    ('infrastructure', 'landslide', 'exposure', 'social vulnerability urban infrastructure index', 'negative', 'IPEA'),
    ('infrastructure', 'landslide', 'exposure', 'road density', 'positive', 'Globio'),
    ('infrastructure', 'landslide', 'exposure', 'railroad density', 'positive', 'ANTAQ'),
    ('infrastructure', 'erosions', 'hazard', 'maximum precipitation 5 days', 'positive', 'Adapta'),
    ('infrastructure', 'erosions', 'vulnerability', 'forest cover', 'negative', 'WorldBank'),
    ('infrastructure', 'erosions', 'vulnerability', 'industry gdp', 'positive', 'IBGE'),
    ('infrastructure', 'erosions', 'exposure', 'social vulnerability urban infrastructure index', 'negative', 'IPEA'),
    ('infrastructure', 'erosions', 'exposure', 'road density', 'positive', 'Globio'),
    ('infrastructure', 'erosions', 'exposure', 'railroad density', 'positive', 'ANTAQ'),
    ('infrastructure', 'heatwaves', 'hazard', 'maximum temperature', 'positive', 'Adapta'),
    ('infrastructure', 'heatwaves', 'vulnerability', 'industry gdp', 'positive', 'IBGE'),
    ('infrastructure', 'heatwaves', 'vulnerability', 'forest cover', 'negative', 'WorldBank'),
    ('infrastructure', 'heatwaves', 'exposure', 'social vulnerability urban infrastructure index', 'negative', 'IPEA'),
    ('biodiversity', 'drought', 'hazard', 'consecutive dry days', 'positive', 'Adapta'),
    ('biodiversity', 'drought', 'vulnerability', 'biodiversity intactness index', 'positive', 'EarthEngine'),
    ('biodiversity', 'drought', 'vulnerability', 'areas of global conservation value', 'positive', 'EarthEngine'),
    ('biodiversity', 'drought', 'exposure', 'protected area', 'positive', 'WDPA'),
    ('biodiversity', 'drought', 'exposure', 'forest and non-forest natural cover', 'positive', 'MapBiomass'),
    ('biodiversity', 'heatwaves', 'hazard', 'maximum temperature', 'positive', 'Adapta'),
    ('biodiversity', 'heatwaves', 'vulnerability', 'biodiversity intactness index', 'positive', 'EarthEngine'),
    ('biodiversity', 'heatwaves', 'vulnerability', 'areas of global conservation value', 'positive', 'EarthEngine'),
    ('biodiversity', 'heatwaves', 'exposure', 'protected area', 'positive', 'WDPA'),
    ('biodiversity', 'heatwaves', 'exposure', 'forest and non-forest natural cover', 'positive', 'MapBiomass')
) AS t(keyimpact_name, hazard_name, component, indicator_name, relationship, datasource);