import sys
import subprocess
import json
import pandas as pd
from state.agent_state import AgentState
from utils.create_prompt import create_prompt
from utils.agent_creation import create_coding_agent
from utils.json_output_cleaner import clean_json_output
from context.mappings.mappings_methodologies import methodologies_mapping
from utils.path_helper import get_run_path, ensure_path_exists
from utils.gemini_mitigation import invoke_with_retry


def extract_methodology_name_agent_step_4(
    state: AgentState,
):
    """
    This agent extracts the GPC 'methodology_name' based on the GPC 'activity_name' and the GPC reference number of the dataframe 'df'.

    Inputs:
        Input path to the csv file created by the prior agent.
        The dataframe loaded from the input path.
        The context for identifying the GPC methodology names.
        The python script generated by the prior agent.
        Output path for the generated files.
    """
    print("\nEXTRACT METHODOLOGY NAME AGENT STEP 4\n")

    # Load the output files of initial script
    input_path_csv = get_run_path(state, "step_3/final/final_output.csv")
    input_path_script = get_run_path(state, "step_3/final/final_output.py")

    # Load the csv file into the dataframe
    df = pd.read_csv(input_path_csv, encoding="utf-8")
    # Load the script
    with open(input_path_script, "r", encoding="utf-8") as file:
        script = file.read()

    # Define the output paths
    output_path_csv = get_run_path(state, "step_4/steps/extracted_methodology_name.csv")
    output_path_script = get_run_path(state, "step_4/steps/generated_script_extracted_methodology_name.py")
    output_path_markdown = get_run_path(state, "step_4/steps/generated_markdown_extracted_methodology_name.md")
    
    # Ensure output directories exist
    ensure_path_exists(output_path_csv)
    ensure_path_exists(output_path_script)
    ensure_path_exists(output_path_markdown)

    task = """
Your task is to extract the Global Protocol for Community-Scale Greenhouse Gas Emission Inventories (GPC) 'methodology name' from the provided python pandas dataframe based on the instructions below. You will also create a runnable python script.
Your inputs are:
- the input path to the .csv file created by the prior agent under <input_path> tags below,
- the dataframe 'df' loaded from the .csv file created by the prior agent, 
- the prior script provided below inside <prior_script> tags, 
- mappings for identifying methodology names in <mappings_methodologies> tags. 
- the output path for the new .csv file under <output_path> tags.
"""

    completion_steps = f"""
a. Inspect the .csv file provided under <input_path> tags below. You are provided with a pandas dataframe 'df' based on this .csv file. Base your further analysis only on this dataframe 'df'. This is already an updated dataframe based on the python script under <prior_script> tags below.
    - NEVER load the .csv file saved in the 'original_path' variable inside the script under <prior_script> tags below.
b. Inspect the mapping for identifying the GPC 'methodology name' in <mappings_methodologies> tags.
c. Inspect the provided python script under <prior_script> tags.
d. Inspect the columns 'activity_name' and 'gpc_refno' of the dataframe 'df'. 
- These two columns determine the correct GPC 'methodology name' based on the provided mapping in <mappings_methodologies> tags. If no GPC 'methodology name' can be determined, return a default value 'unknown' and flag this in your reasoning.
- Print out the unique values of these two columns to make sure to include every unique value in your answer.
- Then map these two identified columns to one of the 4 methodology names ('fuel_combustion_consumption', 'energy_consumption', 'fuel_sales', 'movement_driver') inside the mapping dictionary provided within <mappings_methodologies> tags below for each row.
e. Create a python script based on the script provided within <prior_script> tags. This python script must contain the following:
    1. the original code of the prior script provided in the <prior_script> tags. You make your changes to this script. 
    2. a mapping dictionary for the GPC 'methodology name' based on your prior analysis in step 'd'. The mapping should map between the GPC 'methodology name', the GPC 'activity name' and the GPC reference number.
    3. add a column 'methodology_name' to the dataframe 'df_new' which applies a mapping for the GPC 'methodology name' to each row of 'df_new' based on the created mapping dictionary.
    4. finally:
    - add code to output a new .csv file 'df_new.to_csv' so that the new .csv file contains the new dataframe 'df_new' with the changes made above. The new .csv file must be comma seperated ','. The .csv file must use 'encoding="utf-8"'.
    - store the new path given in <output_path> tags below in the updated variable named 'output_path' for exporting the new .csv file.
    
    IMPORTANT: 
    - The code must contain python comments.
    - The code must be executable and must not contain any code errors.
    - The new script must contain all the content of the initial script in addition to the added data.
    - **NEVER** replace the variable 'original_path' in the script loaded from <prior_script> tags.
"""

    answer_format = """
Your output must be provided in JSON format. Provide all detailed reasoning in a structured and human readable way (e.g. using sub headers, bulletpoints and numbered lists) and the pure executable Python code in the following JSON format:
{
    "reasoning": "Your detailed reasoning here...",
    "code": "Your pure executable Python code here..."
}
Ensure that the output is valid JSON and does not include any additional commentary or explanation. Do not surround the JSON output with any code block markers or tags like ```json```.
"""
    additional_information = f"""
<additional_information>
<input_path>
This is the input path to the .csv file created by the prior agent: {input_path_csv}
</input_path>
<mappings_methodologies>
This is the mapping provided for identifying the methodolgy name: {json.dumps(methodologies_mapping, indent=4)}
</mappings_methodologies>
<prior_script>
This is the prior python script provided:
    
```python
{script}
```
</prior_script>
<output_path>
This is the output path for the new .csv file: {output_path_csv}
</output_path>
</additional_information>
"""

    prompt = create_prompt(
        task, completion_steps, answer_format, additional_information
    )

    # Create agent
    verbose = state.get("verbose", False)
    if verbose is None:
        verbose = False
    agent = create_coding_agent(df, verbose)

    # Invoke summary agent with custom prompt
    response = invoke_with_retry(agent, prompt)
    response_output = response.get("output")

    # Check and potentially clean the JSON output by removing ```json``` code block markers
    cleaned_response_output = clean_json_output(response_output)

    ### Code below for extracting the code from the agent's response and running it - creating the csv file ###
    # Function to parse the JSON response from the agent
    def parse_agent_response(response):
        try:
            response_dict = json.loads(response)
            reasoning = response_dict.get("reasoning", "").strip()
            code = response_dict.get("code", "").strip()
            return {"reasoning": reasoning, "code": code}
        except json.JSONDecodeError as e:
            print(f"JSON decoding failed: {e}")
            sys.exit(1)

    # Parse the agent's response
    output = parse_agent_response(cleaned_response_output)

    # Save the reasoning to a Markdown file
    if output.get("reasoning"):
        with open(output_path_markdown, "w", encoding="utf-8") as markdown_file:
            markdown_file.write(f"# Reasoning\n\n{output['reasoning']}")
    else:
        print("No reasoning was found in the agent's response.")
        sys.exit(1)

    # Save the generated code to a Python file
    if output.get("code"):
        print("Create the script...")
        with open(output_path_script, "w", encoding="utf-8") as script_file:
            script_file.write(output["code"])

        # Run the generated Python script
        print("Attempting to run the generated script...")
        try:
            result = subprocess.run([sys.executable, output_path_script], check=True)
            print("The generated script was executed successfully.")
        except subprocess.CalledProcessError as e:
            print(f"An error occurred while executing the script: {e}")
            sys.exit(1)
    else:
        print("No Python code was found in the agent's response.")
        sys.exit(1)

    return state
