import sys
import subprocess
import json
import pandas as pd
from state.agent_state import AgentState
from utils.create_prompt import create_prompt
from utils.agent_factory import AgentFactory
from utils.create_descriptive_stats_prompt import create_descriptive_stats_prompt
from utils.file_paths_updater import update_file_paths
from utils.path_helper import get_run_path, ensure_path_exists
from utils.gemini_mitigation import invoke_with_retry


def extract_emissions_year_agent_step_2(
    state: AgentState,
):
    """
    This agent is responsible for extracting 'emissions_year' from the data file.
    It will either extract the year from the date column for each row or use the user provided context to determine the year.

    Inputs:
        Input path to the csv file created by the prior agent.
        The dataframe loaded from the input path.
        User provided context about the datafile.
        The python script generated by the prior agent.
    """
    print("\nEXTRACT EMISSIONS YEAR AGENT STEP 2\n")

    # Load the output files of previous step using run paths
    input_path_csv = get_run_path(state, "step_2/steps/1_datasource_name.csv")
    input_path_script = get_run_path(state, "step_2/steps/1_datasource_name.py")

    # Load the csv file into the dataframe
    df = pd.read_csv(input_path_csv, encoding="utf-8")

    # Get pre-initialized agents from the AgentFactory
    verbose = state.get("verbose", False)
    structured_output_agent = AgentFactory.get_structured_output_agent(verbose)
    agent = AgentFactory.get_coding_agent(df, verbose)

    descriptive_statistics = create_descriptive_stats_prompt(df)
    # Load the script
    with open(input_path_script, "r", encoding="utf-8") as file:
        script = file.read()

    # Define the output paths using run paths
    output_path_csv = get_run_path(state, "step_2/steps/2_emissions_year.csv")
    output_path_script = get_run_path(state, "step_2/steps/2_emissions_year.py")
    output_path_markdown = get_run_path(state, "step_2/steps/2_emissions_year.md")
    
    # Ensure output directories exist
    ensure_path_exists(output_path_csv)
    ensure_path_exists(output_path_script)
    ensure_path_exists(output_path_markdown)

    task = """
Your task is to extract the year of the data inside the provided python pandas dataframe. You will also create a runnable python script.
Your inputs are:
- the input path to the .csv file created by the prior agent under <input_path> tags below.
- the dataframe 'df' loaded from the .csv file created by the prior agent.
- user provided context about the datafile in <user_context> tags below.
- the python script created by the prior agent provided inside <prior_script> tags below.
"""

    completion_steps = f"""
a. Inspect the .csv file provided under <input_path> tags below. The dataframe 'df' you are provided with is the result of running the python script under <prior_script> tags below on this input .csv file.
    - When using the Python REPL tool you are provided with, load the .csv file into a pandas dataframe 'df' using the path provided under <input_path> tags and 'df = pd.read_csv(input_path, encoding="utf-8", sep=",")'. **DO NOT** add this code to the python script you are creating.
    - **NEVER** load the .csv file saved in the 'original_path' variable inside the script under <prior_script> tags.  
b. Inspect the user provided context in <user_context> tags for identifying possible information about the year of the data.
c. Determine the year of the data based on the content of the dataframe 'df' and the user provided context. 
- if the dataframe 'df' contains a date column, extract only the year of this date.
- if the dataframe does not contain any dates, inspect if the user provided context contains date information and use it.
- if the year cannot be extracted from the dataframe or the user provided context, use the default value 'NaN' (Not a Number) and flag this in your reasoning.
d. Inspect the provided python script under <prior_script> tags.
e. Update the provided python script in <prior_script> tags below. This python script must contain the following:
    1. the original code of the prior script provided in the <prior_script> tags **WITHOUT** any changes to the exisiting code. 
    2. add a column 'emissions_year' to the dataframe 'df_new' with the extracted data for the year.
    3. Insert the new code at the bottom of the script and before the final output to csv, to keep the chronological order of the script.
    4. **ONLY** insert the new code and **NEVER** overwrite or change the existing code. **NEVER** change the variable 'original_path'.
    

    IMPORTANT: 
    - **DO NOT** load the .csv file saved in the 'original_path' variable inside the script under <prior_script> tags below. You only work with the dataframe 'df' you are already provided with.
    - The code must contain python comments explaining the code.
    - The code must be executable and must not contain any code errors.
    - The new script must contain all the content of the initial script in addition to the added data.
"""

    answer_format = """
Your output must be provided in JSON format. Provide all detailed reasoning in a structured and human readable way (e.g. using sub headers, bulletpoints and numbered lists) and the pure executable Python code in the following JSON format:
{
    "reasoning": "Your detailed reasoning here...",
    "code": "Your pure executable Python code here..."
}
Ensure that the output is valid JSON and does not include any additional commentary or explanation. Do not surround the JSON ooutput with any code block markers or tags like ```json```.
"""
    additional_information = f"""
<additional_information>
<input_path>
This is the input path to the .csv file created by the prior agent: {input_path_csv}
</input_path>
<user_context>
This is the user context provided: {state.get("user_input")}. If there are conflicting values between different sources, use this user context as the highest priority.
</user_context>
<prior_script>
This is the prior python script provided:
    
```python
{script}
```
</prior_script>
<output_path>
This is the output path for the new .csv file: {output_path_csv}
</output_path>
</additional_information>
"""

    prompt = create_prompt(
        task, completion_steps, answer_format, additional_information
    )

    # Invoke summary agent with custom prompt
    full_prompt = descriptive_statistics + prompt
    response = invoke_with_retry(agent, full_prompt)
    response_output = response.get("output")

    # Invoke the new structured output agent with the parsing task
    structured_output = invoke_with_retry(structured_output_agent, response_output)

    ### Code below for extracting the code from the agent's response and running it - creating the csv file ###
    # Function to parse the JSON response from the agent
    def parse_agent_response(response):
        try:
            # Load the pydantic object into JSON
            response_json = response.json()
            # Load the JSON into a dictionary
            response_dict = json.loads(response_json)
            reasoning = response_dict.get("reasoning", "").strip()
            code = response_dict.get("code", "").strip()
            return {"reasoning": reasoning, "code": code}
        except json.JSONDecodeError as e:
            print(f"JSON decoding failed: {e}")
            sys.exit(1)

    # Parse the agent's response
    output = parse_agent_response(structured_output)

    # Save the reasoning to a Markdown file
    if output.get("reasoning"):
        with open(output_path_markdown, "w", encoding="utf-8") as markdown_file:
            markdown_file.write(f"# Reasoning\n\n{output['reasoning']}")
    else:
        print("No reasoning was found in the agent's response.")
        sys.exit(1)

    # Save the generated code to a Python file
    if output.get("code"):
        print("Update file paths...")
        # Update the generated code to replace the file paths dynamically
        updated_code = update_file_paths(
            output["code"], state.get("full_path"), output_path_csv
        )

        print("Create the script...")
        # Save the generated code to a Python file
        with open(output_path_script, "w", encoding="utf-8") as script_file:
            script_file.write(updated_code)

        # Run the generated Python script
        print("Attempting to run the generated script...")
        try:
            result = subprocess.run([sys.executable, output_path_script], check=True)
            print("The generated script was executed successfully.")
        except subprocess.CalledProcessError as e:
            print(f"An error occurred while executing the script: {e}")
            sys.exit(1)
    else:
        print("No Python code was found in the agent's response.")
        sys.exit(1)
    
    # Return the state to pass to next agent
    return state
