SELECT  'Google EIE' AS source_name,
        'II.1.1' as gpc_reference_number,
        '{{ city_name }}' as actor_name,
        '{{locode}}' as actor_id,
        'annual' as temporal_granularity,
        'Induced activity' as method_name,
        'VKT' as activity_name,
        json_object('tranportation mode:', lower(_mode),
                     'trip direction:', lower(travel_bounds)) as activity_subcategory_type,
        gpc_distance_km as activity_value,
        'km' as activity_units,
        'co2e' as gas_name,
        gpc_co2e_tons*1000 as emissions_value,
        'kg' as emissions_units,
        _year as emissions_year,
        null as emissions_factor_id, 
        null as geometry_type,
        null as geometry_value  
FROM {{ df_1 }}