WITH raw_data AS (
    SELECT 
        action_id,
        action_name::json AS action_name,
        action_type::VARCHAR[] AS action_type,
        hazard_name::VARCHAR[] AS hazard_name,
        sector_names::VARCHAR[] AS sector_names,
        subsector_names::VARCHAR[] AS subsector_names,
        primary_purpose::VARCHAR[] AS primary_purpose,
        description::json AS description,
        cobenefits_airquality::INTEGER AS cobenefits_airquality,
        cobenefits_waterquality::INTEGER AS cobenefits_waterquality,
        cobenefits_habitat::INTEGER AS cobenefits_habitat,
        cobenefits_costofliving::INTEGER AS cobenefits_costofliving,
        cobenefits_housing::INTEGER AS cobenefits_housing,
        cobenefits_mobility::INTEGER AS cobenefits_mobility,
        cobenefits_stakeholderengagement::INTEGER AS cobenefits_stakeholderengagement,
        equity_and_inclusion_considerations::json AS equity_and_inclusion_considerations,
        ghgreduction_stationary_energy::VARCHAR AS ghgreduction_stationary_energy,
        ghgreduction_transportation::VARCHAR AS ghgreduction_transportation,
        ghgreduction_waste::VARCHAR AS ghgreduction_waste,
        ghgreduction_ippu::VARCHAR AS ghgreduction_ippu,
        ghgreduction_afolu::VARCHAR AS ghgreduction_afolu,
        adaptation_effectiveness::VARCHAR AS adaptation_effectiveness,
        cost_investment_needed::VARCHAR AS cost_investment_needed,
        timeline_for_implementation::VARCHAR AS timeline_for_implementation,
        dependencies::json AS dependencies,
        key_performance_indicators::json AS key_performance_indicators,
        powers_and_mandates::VARCHAR[] AS powers_and_mandates,
        replace(adaptation_effectiveness_droughts::VARCHAR, '"', '') AS adaptation_effectiveness_droughts,
        replace(adaptation_effectiveness_heatwaves::VARCHAR, '"', '') AS adaptation_effectiveness_heatwaves,
        replace(adaptation_effectiveness_floods::VARCHAR, '"', '') AS adaptation_effectiveness_floods,
        replace(adaptation_effectiveness_sealevelrise::VARCHAR, '"', '') AS adaptation_effectiveness_sealevelrise,
        replace(adaptation_effectiveness_landslides::VARCHAR, '"', '') AS adaptation_effectiveness_landslides,
        replace(adaptation_effectiveness_storms::VARCHAR, '"', '') AS adaptation_effectiveness_storms,
        replace(adaptation_effectiveness_wildfires::VARCHAR, '"', '') AS adaptation_effectiveness_wildfires,
        replace(adaptation_effectiveness_diseases::VARCHAR, '"', '') AS adaptation_effectiveness_diseases,
        biome::VARCHAR AS biome
    FROM raw_data.cap_climate_action
)
INSERT INTO modelled.cap_climate_action (
    action_id,
    action_name,
    action_type,
    hazard_name,
    sector_names,
    subsector_names,
    primary_purpose,
    description,
    cobenefits_airquality,
    cobenefits_waterquality,
    cobenefits_habitat,
    cobenefits_costofliving,
    cobenefits_housing,
    cobenefits_mobility,
    cobenefits_stakeholderengagement,
    equity_and_inclusion_considerations,
    ghgreduction_stationary_energy,
    ghgreduction_transportation,
    ghgreduction_waste,
    ghgreduction_ippu,
    ghgreduction_afolu,
    adaptation_effectiveness,
    cost_investment_needed,
    timeline_for_implementation,
    dependencies,
    key_performance_indicators,
    powers_and_mandates,
    adaptation_effectiveness_droughts,
    adaptation_effectiveness_heatwaves,
    adaptation_effectiveness_floods,
    adaptation_effectiveness_sealevelrise,
    adaptation_effectiveness_landslides,
    adaptation_effectiveness_storms,
    adaptation_effectiveness_wildfires,
    adaptation_effectiveness_diseases,
    biome
)
SELECT
    action_id,
    action_name,
    action_type,
    hazard_name,
    sector_names,
    subsector_names,
    primary_purpose,
    description,
    cobenefits_airquality,
    cobenefits_waterquality,
    cobenefits_habitat,
    cobenefits_costofliving,
    cobenefits_housing,
    cobenefits_mobility,
    cobenefits_stakeholderengagement,
    equity_and_inclusion_considerations,
    ghgreduction_stationary_energy,
    ghgreduction_transportation,
    ghgreduction_waste,
    ghgreduction_ippu,
    ghgreduction_afolu,
    adaptation_effectiveness,
    cost_investment_needed,
    timeline_for_implementation,
    dependencies,
    key_performance_indicators,
    powers_and_mandates,
    adaptation_effectiveness_droughts,
    adaptation_effectiveness_heatwaves,
    adaptation_effectiveness_floods,
    adaptation_effectiveness_sealevelrise,
    adaptation_effectiveness_landslides,
    adaptation_effectiveness_storms,
    adaptation_effectiveness_wildfires,
    adaptation_effectiveness_diseases,
    case when biome ='none' then null else biome end as biome
FROM raw_data
ON CONFLICT (action_id) DO UPDATE SET
    action_name = EXCLUDED.action_name,
    action_type = EXCLUDED.action_type,
    hazard_name = EXCLUDED.hazard_name,
    sector_names = EXCLUDED.sector_names,
    subsector_names = EXCLUDED.subsector_names,
    primary_purpose = EXCLUDED.primary_purpose,
    description = EXCLUDED.description,
    cobenefits_airquality = EXCLUDED.cobenefits_airquality,
    cobenefits_waterquality = EXCLUDED.cobenefits_waterquality,
    cobenefits_habitat = EXCLUDED.cobenefits_habitat,
    cobenefits_costofliving = EXCLUDED.cobenefits_costofliving,
    cobenefits_housing = EXCLUDED.cobenefits_housing,
    cobenefits_mobility = EXCLUDED.cobenefits_mobility,
    cobenefits_stakeholderengagement = EXCLUDED.cobenefits_stakeholderengagement,
    equity_and_inclusion_considerations = EXCLUDED.equity_and_inclusion_considerations,
    ghgreduction_stationary_energy = EXCLUDED.ghgreduction_stationary_energy,
    ghgreduction_transportation = EXCLUDED.ghgreduction_transportation,
    ghgreduction_waste = EXCLUDED.ghgreduction_waste,
    ghgreduction_ippu = EXCLUDED.ghgreduction_ippu,
    ghgreduction_afolu = EXCLUDED.ghgreduction_afolu,
    adaptation_effectiveness = EXCLUDED.adaptation_effectiveness,
    cost_investment_needed = EXCLUDED.cost_investment_needed,
    timeline_for_implementation = EXCLUDED.timeline_for_implementation,
    dependencies = EXCLUDED.dependencies,
    key_performance_indicators = EXCLUDED.key_performance_indicators,
    powers_and_mandates = EXCLUDED.powers_and_mandates,
    adaptation_effectiveness_droughts = EXCLUDED.adaptation_effectiveness_droughts,
    adaptation_effectiveness_heatwaves = EXCLUDED.adaptation_effectiveness_heatwaves,
    adaptation_effectiveness_floods = EXCLUDED.adaptation_effectiveness_floods,
    adaptation_effectiveness_sealevelrise = EXCLUDED.adaptation_effectiveness_sealevelrise,
    adaptation_effectiveness_landslides = EXCLUDED.adaptation_effectiveness_landslides,
    adaptation_effectiveness_storms = EXCLUDED.adaptation_effectiveness_storms,
    adaptation_effectiveness_wildfires = EXCLUDED.adaptation_effectiveness_wildfires,
    adaptation_effectiveness_diseases = EXCLUDED.adaptation_effectiveness_diseases,
    biome = EXCLUDED.biome;